#!usr/bin/env python3.5
'''
reference = notebook 8.7b

corrects plink's filtering of r2 = 0 correlations in r2 calculations.

takes in input generated by r2filemaker.R

usage:
python3.5 zerocorrector.py <df file> > <outfile name>
'''

import sys
import pandas as pd

def ranger(snppos, df):
    '''Takes a SNP position, a df of all pairwise comparisons,
    and returns positions of SNPs that haven't been subject to comparisons.'''
    subdf = df[df.pos1 == snppos] # existing r2 calculations
    totrange = df[[all([a, b]) for a, b in zip(df.pos2 <= snppos + 100000, df.pos2 > snppos)]] # all pairs
    inrange = [int(num[0]) for num in subdf[['pos2']].values.tolist()]
    totrange = [int(num[0]) for num in totrange[['pos2']].values.tolist()]
    snplist = [pos for pos in totrange if pos not in inrange] # list of excluded pairs
    snplist = list(set(snplist))
    return snplist

def zeroadder(df, snp):
    '''Given a SNP and a df of correlations, appends the df with correlations
    that weren't done by plink and gives them zero values.'''
    snplist = ranger(snp, df)
    if snplist:
        for num in snplist:
            print(snp, num, 0)
    if not snplist: # ie snplist is empty
        pass

def pairwisedoer(df):
    '''Applies zeroadder across all SNPs in a df.'''
    allsnps = [int(num[0]) for num in df[['pos1']].values.tolist()]
    for snp in allsnps:
        snp = int(snp)
        out = zeroadder(df, snp)
        if out is not None:
            print(out)
    
# analysis

dfname = str(sys.argv[1])
data = pd.read_csv(dfname, header = 'infer') # read in file
data.drop(data.columns[[0]], axis = 1, inplace = True) # cleanup

print('pos1', 'pos2', 'r2') # initialize headers

for i in range(data.shape[0]):
    print(int(data.iloc[i,0]), int(data.iloc[i,1]), data.iloc[i,2])

pairwisedoer(data) 
